export const SOCKET_EVENTS = {
  CONNECT: 'connect',
  DISCONNECT: 'disconnect',
  CONNECT_ERROR: 'connect_error',
  JOIN_ROOM: 'room:join',
  LEAVE_ROOM: 'room:leave',
  NOTIFICATION_NEW: 'notification:new',
  INCIDENT_CREATED: 'incident:created',
  INCIDENT_UPDATED: 'incident:updated',
  INCIDENT_RESOLVED: 'incident:resolved',
  INCIDENT_CLOSED: 'incident:closed',
  TASK_ASSIGNED: 'volunteer:assigned',
  TASK_ACCEPTED: 'volunteer:accepted',
  TASK_COMPLETED: 'volunteer:completed',
  CROWD_UPDATED: 'crowd:updated',
  DASHBOARD_UPDATED: 'dashboard:updated',
  MAP_UPDATED: 'map:updated',
  AI_SUMMARY_GENERATED: 'ai:summary:generated',
  AI_RECOMMENDATION: 'ai:recommendation',
  EMERGENCY_ALERT: 'emergency:alert',
  EMERGENCY_RESOLVED: 'emergency:resolved',
  EMERGENCY_BROADCAST_ACTIVE: 'emergency.broadcast.active',
  EMERGENCY_BROADCAST_RESOLVED: 'emergency.broadcast.resolved'
};
