export const STATUS = {
  HEALTHY: 'HEALTHY',
  DEGRADED: 'DEGRADED',
  CRITICAL: 'CRITICAL',
  OFFLINE: 'OFFLINE',
  UNKNOWN: 'UNKNOWN'
};

export const THRESHOLDS = {
  // DB
  DB_LATENCY_DEGRADED: 100, // ms
  DB_LATENCY_CRITICAL: 500, // ms
  
  // API
  API_LATENCY_DEGRADED: 500, // ms
  API_LATENCY_CRITICAL: 1500, // ms
  API_ERROR_RATE_DEGRADED: 2, // percentage
  API_ERROR_RATE_CRITICAL: 5, // percentage
  
  // Socket
  SOCKET_DISCONNECT_RATE_DEGRADED: 5, // percentage
  SOCKET_DISCONNECT_RATE_CRITICAL: 15, // percentage
  
  // AI
  AI_LATENCY_DEGRADED: 2000, // ms
  AI_LATENCY_CRITICAL: 5000, // ms
  AI_FAILURE_RATE_DEGRADED: 5, // percentage
  AI_FAILURE_RATE_CRITICAL: 20, // percentage
  
  // Score Bands
  SCORE_HEALTHY: 90,
  SCORE_DEGRADED: 75,
  SCORE_HIGH_RISK: 50
};

export const SYSTEM_INCIDENT_TYPES = {
  DATABASE_DOWN: 'DATABASE_DOWN',
  DATABASE_LATENCY: 'DATABASE_LATENCY',
  HIGH_API_LATENCY: 'HIGH_API_LATENCY',
  HIGH_ERROR_RATE: 'HIGH_ERROR_RATE',
  SOCKET_DEGRADED: 'SOCKET_DEGRADED',
  AI_PROVIDER_DOWN: 'AI_PROVIDER_DOWN',
  AI_HIGH_FAILURE_RATE: 'AI_HIGH_FAILURE_RATE'
};

export const SERVICES = {
  MONGODB: 'MongoDB',
  REST_API: 'REST_API',
  SOCKET: 'Socket.io',
  AI: 'Groq_AI'
};
